name: Kurt_Karpov
favicon: null
layout_spectrum: 0.92311
typography_spectrum: 0.8675744342617691
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e2dfcc'
    - '#3f4042'
    - '#b14d33'
    - '#787d80'
  brandStrength: 0.5625
  lightness: 0.4375
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
