name: Kurt_Karpov
favicon: null
layout_spectrum: 1
typography_spectrum: 0.65799
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e6e8e5'
    - '#5c81ad'
    - '#1c2a2b'
    - '#afbdc6'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
